const { test, describe, beforeEach, after} = require('node:test')
const assert = require('node:assert')
const supertest = require('supertest')
const Blog = require('../models/Blog')
const app = require('../app')
const mongoose = require('mongoose')
const api = supertest(app)

// mock data generated by GPT
const blogs = [
    {
        title: "React patterns",
        author: "Michael Chan",
        url: "https://reactpatterns.com/",
        likes: 7
    },
    {
        title: "Go To Statement Considered Harmful",
        author: "Edsger W. Dijkstra",
        url: "http://www.u.arizona.edu/~rubinson/copyright_violations/Go_To_Considered_Harmful.html",
        likes: 5
    },
    {
        title: "Canonical string reduction",
        author: "Edsger W. Dijkstra",
        url: "http://www.cs.utexas.edu/~EWD/transcriptions/EWD08xx/EWD808.html",
        likes: 12
    },
    {
        title: "First class tests",
        author: "Robert C. Martin",
        url: "http://blog.cleancoder.com/uncle-bob/2017/05/05/TestDefinitions.htmll",
        likes: 10
    },
    {
        title: "TDD harms architecture",
        author: "Robert C. Martin",
        url: "http://blog.cleancoder.com/uncle-bob/2017/03/03/TDD-Harms-Architecture.html",
        likes: 0
    },
    {
        title: "Type wars",
        author: "Robert C. Martin",
        url: "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
        likes: 2
    }
]

// initialize database
beforeEach(async () => {
    await Blog.deleteMany({})
    for(let blog of blogs) {
        let blogObject = new Blog(blog)
        await blogObject.save()
    }
})

describe('Blog API tests', () => {
    test('blogs are returned as json', async () => {
        const response = await api.get('/api/blogs')
        assert.strictEqual(response.status, 200)
        assert.match(response.headers['content-type'], /application\/json/)
    })
    test('all blogs are returned', async () => {
        const response = await api.get('/api/blogs')
        assert.strictEqual(response.body.length, blogs.length)
    })
    test('the unique identifier property of the blog posts should be named id', async () => {
        const response = await api.get('/api/blogs')
        for(let blog of response.body) {
            assert.ok(blog.id)
        }
    })
    test('a valid blog can be added', async () => {
        const newBlog = {
            title: "New blog post",
            author: "Test Author",
            url: "http://example.com/new-blog-post",
            likes: 10
        }
        await api
            .post('/api/blogs')
            .send(newBlog)
            .expect(201)
        assert.strictEqual((await Blog.countDocuments({})), blogs.length + 1)
    })
    test('if the likes property is missing from the request, it will default to 0', async () => {
        const newBlog = {
            title: "New blog post",
            author: "Test Author",
            url: "http://example.com/new-blog-post",
        }
        const response = await api
            .post('/api/blogs')
            .send(newBlog)
            .expect(201)
        assert.strictEqual(response.body.likes,0)
    })
    test('missing title results in 400',async() => {
        const newBlog = {
            author: "Test Author",
            likes: 0,
            url: "http://example.com/new-blog-post"
        }
        await api
            .post('/api/blogs')
            .send(newBlog)
            .expect(400)
    })
    test('missing url results in 400',async() => {
        const newBlog = {
            title: "New blog post",
            author: "Test Author",
            likes: 0
        }
        await api
            .post('/api/blogs')
            .send(newBlog)
            .expect(400)
    })
    test('DELETE /api/blogs/:id deletes a blog', async () => {
        const blogsAtStart = await Blog.find({})
        const blogToDelete = blogsAtStart[0]

        await api
            .delete(`/api/blogs/${blogToDelete._id}`)
            .expect(204)

        const blogsAtEnd = await Blog.find({})
        assert.strictEqual(blogsAtEnd.length, blogsAtStart.length - 1)
        const titles = blogsAtEnd.map(b => b.title)
        assert(!titles.includes(blogToDelete.title))
    })
    test('PUT /api/blogs/:id updates a blog', async () => {
        const blogsAtStart = await Blog.find({})
        const blogToUpdate = blogsAtStart[0]

        const updatedData = { likes: 10 }
        const response = await api
            .put(`/api/blogs/${blogToUpdate._id}`)
            .send(updatedData)
            .expect(200)
            .expect('Content-Type', /application\/json/)

        assert.strictEqual(response.body.likes, 10)
        assert.strictEqual(response.body.title, blogToUpdate.title)
        assert.strictEqual(response.body.author, blogToUpdate.author)
    })
})




after(async () => {
    await mongoose.connection.close()
})